# Generated by Django 5.2.17 on 2026-09-17 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("partnership", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="partnership",
            name="attachment",
            field=models.FileField(
                blank=True, max_length=500, null=True, upload_to="partnerships/"
            ),
        ),
    ]
