# Generated by Django 5.2.17 on 2026-10-09 10:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Event",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField()),
                ("content", models.TextField()),
                ("banner_image", models.ImageField(upload_to="event_banners/")),
                ("date", models.DateTimeField()),
                ("location", models.CharField(max_length=200)),
                ("is_online", models.BooleanField(default=False)),
                ("meeting_link", models.URLField(blank=True, null=True)),
                ("organizer_name", models.CharField(max_length=200)),
                (
                    "organizer_logo",
                    models.ImageField(
                        blank=True, null=True, upload_to="organizer_logos/"
                    ),
                ),
                (
                    "tags",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text='List of tags e.g. ["Workshop", "Webinar", "AI"]',
                    ),
                ),
                (
                    "registration_status",
                    models.CharField(
                        choices=[
                            ("open", "Open"),
                            ("closed", "Closed"),
                            ("full", "Full"),
                        ],
                        default="open",
                        max_length=20,
                    ),
                ),
                ("is_featured", models.BooleanField(default=False)),
                (
                    "display_order",
                    models.PositiveIntegerField(db_index=True, default=0),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Event",
                "verbose_name_plural": "Events",
                "ordering": ["display_order", "-date"],
            },
        ),
        migrations.CreateModel(
            name="EventImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="event_gallery/")),
                ("order", models.IntegerField(default=0)),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="gallery_images",
                        to="events.event",
                    ),
                ),
            ],
            options={
                "verbose_name": "Event Image",
                "verbose_name_plural": "Event Images",
                "ordering": ["order"],
            },
        ),
    ]
