# Generated by Django 5.2.15 on 2026-08-31 04:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AboutSection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "section_type",
                    models.CharField(
                        choices=[
                            ("MISSION", "Mission"),
                            ("VISION", "Vision"),
                            ("GOALS", "Goals"),
                            ("HISTORY", "History"),
                            ("CONSTITUTION", "Constitution & By-Laws"),
                            ("RESOLUTION", "Resolution"),
                            ("CUSTOM", "Custom"),
                        ],
                        default="CUSTOM",
                        max_length=20,
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("body", models.TextField(blank=True, default="")),
                ("document", models.FileField(blank=True, upload_to="org_documents/")),
                (
                    "document_name",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                ("is_published", models.BooleanField(default=True)),
                (
                    "display_order",
                    models.PositiveIntegerField(db_index=True, default=0),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="about_sections",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "About Section",
                "verbose_name_plural": "About Sections",
                "ordering": ["display_order", "created_at"],
            },
        ),
    ]
