# Generated by Django 4.2.7 on 2026-06-06 19:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('action_type', models.CharField(choices=[('MEMBER_APPROVED', 'Member Approved'), ('MEMBER_REJECTED', 'Member Rejected'), ('MEMBER_CREATED', 'Member Created'), ('MEMBER_UPDATED', 'Member Updated'), ('MEMBER_DELETED', 'Member Deleted'), ('ROLE_ASSIGNED', 'Role Assigned'), ('ROLE_DELEGATED', 'Role Delegated'), ('ADMIN_CREATED', 'Admin Created'), ('ADMIN_UPDATED', 'Admin Updated'), ('ADMIN_DELETED', 'Admin Deleted'), ('MILESTONE_CREATED', 'Milestone Created'), ('MILESTONE_UPDATED', 'Milestone Updated'), ('MILESTONE_DELETED', 'Milestone Deleted'), ('MILESTONE_IMAGE_UPLOADED', 'Milestone Image Uploaded'), ('MILESTONE_IMAGE_DELETED', 'Milestone Image Deleted'), ('ANNOUNCEMENT_CREATED', 'Announcement Created'), ('ANNOUNCEMENT_UPDATED', 'Announcement Updated'), ('ANNOUNCEMENT_DELETED', 'Announcement Deleted'), ('ANNOUNCEMENT_IMAGE_UPLOADED', 'Announcement Image Uploaded'), ('ANNOUNCEMENT_IMAGE_DELETED', 'Announcement Image Deleted'), ('YEAR_END_RESET', 'Year-End Reset'), ('PAYMENT_SETTINGS_UPDATED', 'Payment Settings Updated')], db_index=True, max_length=50)),
                ('entity_type', models.CharField(choices=[('Member', 'Member'), ('User', 'User'), ('Milestone', 'Milestone'), ('Announcement', 'Announcement'), ('PaymentSettings', 'Payment Settings')], db_index=True, max_length=50)),
                ('entity_id', models.IntegerField(blank=True, db_index=True, null=True)),
                ('entity_name', models.CharField(blank=True, max_length=255)),
                ('details', models.JSONField(blank=True, default=dict)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('admin_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Audit Log',
                'verbose_name_plural': 'Audit Logs',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['timestamp'], name='audit_logs__timesta_aec53a_idx'), models.Index(fields=['action_type'], name='audit_logs__action__6cd600_idx'), models.Index(fields=['entity_type'], name='audit_logs__entity__5f3d85_idx'), models.Index(fields=['-timestamp'], name='audit_logs__timesta_63825c_idx')],
            },
        ),
    ]
