# Generated by Django 5.2.15 on 2026-08-31 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("audit_logs", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="auditlog",
            name="action_type",
            field=models.CharField(
                choices=[
                    ("MEMBER_APPROVED", "Member Approved"),
                    ("MEMBER_REJECTED", "Member Rejected"),
                    ("MEMBER_CREATED", "Member Created"),
                    ("MEMBER_UPDATED", "Member Updated"),
                    ("MEMBER_DELETED", "Member Deleted"),
                    ("ROLE_ASSIGNED", "Role Assigned"),
                    ("ROLE_DELEGATED", "Role Delegated"),
                    ("ADMIN_CREATED", "Admin Created"),
                    ("ADMIN_UPDATED", "Admin Updated"),
                    ("ADMIN_DELETED", "Admin Deleted"),
                    ("MILESTONE_CREATED", "Milestone Created"),
                    ("MILESTONE_UPDATED", "Milestone Updated"),
                    ("MILESTONE_DELETED", "Milestone Deleted"),
                    ("MILESTONE_IMAGE_UPLOADED", "Milestone Image Uploaded"),
                    ("MILESTONE_IMAGE_DELETED", "Milestone Image Deleted"),
                    ("ANNOUNCEMENT_CREATED", "Announcement Created"),
                    ("ANNOUNCEMENT_UPDATED", "Announcement Updated"),
                    ("ANNOUNCEMENT_DELETED", "Announcement Deleted"),
                    ("ANNOUNCEMENT_IMAGE_UPLOADED", "Announcement Image Uploaded"),
                    ("ANNOUNCEMENT_IMAGE_DELETED", "Announcement Image Deleted"),
                    ("ABOUT_SECTION_CREATED", "About Section Created"),
                    ("ABOUT_SECTION_UPDATED", "About Section Updated"),
                    ("ABOUT_SECTION_DELETED", "About Section Deleted"),
                    ("ABOUT_SECTION_REORDERED", "About Section Reordered"),
                    ("YEAR_END_RESET", "Year-End Reset"),
                    ("PAYMENT_SETTINGS_UPDATED", "Payment Settings Updated"),
                ],
                db_index=True,
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="auditlog",
            name="entity_type",
            field=models.CharField(
                choices=[
                    ("Member", "Member"),
                    ("User", "User"),
                    ("Milestone", "Milestone"),
                    ("Announcement", "Announcement"),
                    ("About", "About"),
                    ("PaymentSettings", "Payment Settings"),
                ],
                db_index=True,
                max_length=50,
            ),
        ),
    ]
