# Generated by Django 4.2.7 on 2026-06-01 00:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Milestone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('headline', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('content', models.TextField()),
                ('date', models.DateField()),
                ('category', models.CharField(choices=[('founding', 'Founding'), ('achievement', 'Achievement'), ('recognition', 'Recognition'), ('event', 'Event'), ('community', 'Community')], default='achievement', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Milestone',
                'verbose_name_plural': 'Milestones',
                'ordering': ['-date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MilestoneImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='milestone_images/')),
                ('order', models.IntegerField(default=0)),
                ('milestone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='milestones.milestone')),
            ],
            options={
                'verbose_name': 'Milestone Image',
                'verbose_name_plural': 'Milestone Images',
                'ordering': ['order'],
            },
        ),
    ]
