# Generated by Django 4.2.7 on 2026-06-25 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('milestones', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='milestone',
            name='category',
            field=models.CharField(choices=[('founding', 'Founding'), ('achievement', 'Achievement'), ('recognition', 'Recognition'), ('event', 'Event'), ('community', 'Community'), ('feature', 'Feature')], default='achievement', max_length=20),
        ),
    ]
