# Generated by Django 4.2.7 on 2026-07-24 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('milestones', '0002_alter_milestone_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='milestone',
            options={'ordering': ['display_order', '-date'], 'verbose_name': 'Milestone', 'verbose_name_plural': 'Milestones'},
        ),
        migrations.AddField(
            model_name='milestone',
            name='display_order',
            field=models.PositiveIntegerField(db_index=True, default=0),
        ),
    ]
