# Generated by Django 4.2.7 on 2026-05-29 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='memberprofile',
            name='payment_method',
            field=models.CharField(choices=[('ON_HAND', 'On-hand / Personal'), ('GCASH', 'GCash')], default='ON_HAND', max_length=10),
        ),
        migrations.AddField(
            model_name='memberprofile',
            name='payment_proof_image',
            field=models.ImageField(blank=True, null=True, upload_to='payment_proofs/'),
        ),
    ]
