# Generated by Django 4.2.7 on 2026-05-30 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0004_paymentsettings_gcash_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='memberprofile',
            name='coe_id_image',
            field=models.ImageField(blank=True, null=True, upload_to='coe_id_documents/', verbose_name='COE/ID Document'),
        ),
    ]
