# Generated by Django 4.2.7 on 2026-06-28 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0006_fix_memberprofile_user_fk'),
    ]

    operations = [
        migrations.AddField(
            model_name='memberprofile',
            name='admin_message',
            field=models.TextField(blank=True, verbose_name='Admin Message'),
        ),
    ]
