# Generated by Django 4.2.7 on 2026-07-14 02:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0007_add_admin_message'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('REGISTRATION', 'Registration'), ('RENEWAL', 'Renewal')], max_length=20)),
                ('payment_method', models.CharField(choices=[('ON_HAND', 'On-hand / Personal'), ('GCASH', 'GCash')], max_length=10)),
                ('payment_proof_image', models.ImageField(blank=True, null=True, upload_to='payment_proofs/')),
                ('receipt_image', models.ImageField(blank=True, max_length=500, null=True, upload_to='receipts/')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('VERIFIED', 'Verified')], default='PENDING', max_length=20)),
                ('reference_number', models.CharField(max_length=30, unique=True)),
                ('academic_year', models.CharField(blank=True, max_length=20)),
                ('approved_by_name', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='members.memberprofile')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
