# Generated by Django 4.2.7 on 2026-08-07 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0008_paymenttransaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymenttransaction',
            name='approved_by_position',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
