# Generated by Django 4.2.7 on 2026-08-12 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0009_paymenttransaction_approved_by_position'),
    ]

    operations = [
        migrations.AddField(
            model_name='memberprofile',
            name='membership_fee',
            field=models.CharField(choices=[('SEMESTER', '₱25 — 1 Semester'), ('ANNUAL', '₱50 — 1 Academic Year')], default='SEMESTER', max_length=10),
        ),
        migrations.AddField(
            model_name='paymenttransaction',
            name='fee_amount',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='memberprofile',
            name='student_number',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
