# Generated by Django 5.2.15 on 2026-08-31 03:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("members", "0010_memberprofile_membership_fee_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="memberprofile",
            name="address",
        ),
        migrations.RemoveField(
            model_name="memberprofile",
            name="birthdate",
        ),
    ]
