# Generated by Django 5.2.17 on 2026-10-09 12:26

from django.db import migrations, models


def rename_annual_to_plus(apps, schema_editor):
    """Data migration to rename ANNUAL to PLUS in existing records"""
    apps.get_model('members', 'MemberProfile').objects.filter(membership_fee='ANNUAL').update(membership_fee='PLUS')


class Migration(migrations.Migration):

    dependencies = [
        ("members", "0011_remove_memberprofile_address_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="memberprofile",
            name="membership_fee",
            field=models.CharField(
                choices=[
                    ("SEMESTER", "₱25 — Regular Membership"),
                    ("PLUS", "₱60 — Membership Plus"),
                ],
                default="SEMESTER",
                max_length=10,
            ),
        ),
        migrations.RunPython(rename_annual_to_plus),
    ]
