# Generated by Django 4.2.7 on 2026-07-16 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('announcements', '0002_announcementimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='members_only',
            field=models.BooleanField(default=False, help_text='If checked, only visible to authenticated members'),
        ),
    ]
