# Generated by Django 5.2.17 on 2026-09-27 17:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("announcements", "0004_alter_announcement_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="announcement",
            name="email_blast_sent_at",
            field=models.DateTimeField(
                blank=True,
                help_text="When an email blast was last triggered for this announcement",
                null=True,
            ),
        ),
        migrations.CreateModel(
            name="BlastLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("recipient_count", models.PositiveIntegerField(default=0)),
                ("sent_count", models.PositiveIntegerField(default=0)),
                ("failed_count", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "announcement",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="blast_logs",
                        to="announcements.announcement",
                    ),
                ),
            ],
            options={
                "verbose_name": "Announcement Blast Log",
                "verbose_name_plural": "Announcement Blast Logs",
                "ordering": ["-created_at"],
            },
        ),
    ]
