# Generated by Django 5.2.17 on 2026-10-06 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("announcements", "0005_announcement_email_blast_sent_at_blastlog"),
    ]

    operations = [
        migrations.AddField(
            model_name="announcement",
            name="links",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="List of URL attachments with structure: [{url, label, description, order}]",
            ),
        ),
    ]
