# Generated by Django 5.2.17 on 2026-10-08 11:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("announcements", "0006_announcement_links"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="announcement",
            name="links",
        ),
    ]
