# Generated by Django 5.2.17 on 2026-10-09 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("announcements", "0007_remove_announcement_links"),
    ]

    operations = [
        migrations.AddField(
            model_name="announcement",
            name="event_date_end",
            field=models.DateField(
                blank=True, help_text="Event end date (optional)", null=True
            ),
        ),
        migrations.AddField(
            model_name="announcement",
            name="event_date_start",
            field=models.DateField(
                blank=True, help_text="Event start date (optional)", null=True
            ),
        ),
        migrations.AddField(
            model_name="announcement",
            name="event_time_end",
            field=models.TimeField(
                blank=True, help_text="Event end time (optional)", null=True
            ),
        ),
        migrations.AddField(
            model_name="announcement",
            name="event_time_start",
            field=models.TimeField(
                blank=True, help_text="Event start time (optional)", null=True
            ),
        ),
        migrations.AddField(
            model_name="announcement",
            name="location",
            field=models.CharField(
                blank=True,
                help_text="Event location (optional)",
                max_length=200,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="announcement",
            name="category",
            field=models.CharField(
                default="Announcement",
                help_text="Category for the announcement (e.g., Announcement, Event, Achievement, etc.)",
                max_length=50,
            ),
        ),
    ]
