# Generated by Django 5.2.17 on 2026-10-09 15:51

from django.db import migrations, models


def convert_category_to_lowercase(apps, schema_editor):
    """Convert existing category values to lowercase to match TextChoices."""
    Announcement = apps.get_model('announcements', 'Announcement')
    
    category_mapping = {
        'Announcement': 'announcement',
        'Achievement': 'achievement',
        'Update': 'update',
        'Opportunity': 'opportunity',
        'Event': 'event',
    }
    
    for announcement in Announcement.objects.all():
        if announcement.category in category_mapping:
            announcement.category = category_mapping[announcement.category]
            announcement.save(update_fields=['category'])
        elif announcement.category not in ['announcement', 'achievement', 'update', 'opportunity', 'event']:
            # Default to announcement for unknown values
            announcement.category = 'announcement'
            announcement.save(update_fields=['category'])


class Migration(migrations.Migration):

    dependencies = [
        ("announcements", "0008_announcement_event_date_end_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="announcement",
            name="tags",
            field=models.CharField(
                blank=True,
                help_text="Comma-separated tags for badges (e.g., urgent, scholarship, competition)",
                max_length=500,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="announcement",
            name="category",
            field=models.CharField(
                choices=[
                    ("announcement", "Announcement"),
                    ("achievement", "Achievement"),
                    ("update", "Update"),
                    ("opportunity", "Opportunity"),
                    ("event", "Event"),
                ],
                default="announcement",
                max_length=20,
            ),
        ),
        migrations.RunPython(convert_category_to_lowercase, migrations.RunPython.noop),
    ]
