# Generated by Django 5.2.17 on 2026-10-09 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("announcements", "0009_announcement_tags_alter_announcement_category"),
    ]

    operations = [
        migrations.AlterField(
            model_name="announcement",
            name="email_blast_sent_at",
            field=models.DateTimeField(
                blank=True,
                help_text="When an email blast was last triggered for this announcement (any published announcement)",
                null=True,
            ),
        ),
    ]
