# Generated by Django 4.2.7 on 2026-06-06 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_user_profile_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='year_level',
            field=models.CharField(blank=True, choices=[('4', '4th Year'), ('3', '3rd Year'), ('2', '2nd Year'), ('1', '1st Year')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='position',
            field=models.CharField(choices=[('NONE', 'None'), ('PRESIDENT', 'President'), ('INTERNAL_VICE_PRESIDENT', 'Internal Vice President'), ('EXTERNAL_VICE_PRESIDENT', 'External Vice President'), ('SECRETARY', 'Secretary'), ('ASSISTANT_SECRETARY', 'Assistant Secretary'), ('FINANCE_EXECUTIVE', 'Finance Executive'), ('ASSISTANT_FINANCE_EXECUTIVE', 'Assistant Finance Executive'), ('AUDITOR', 'Auditor'), ('LOGISTIC', 'Logistic'), ('BUSINESS_MANAGER_1', 'Business Manager 1'), ('BUSINESS_MANAGER_2', 'Business Manager 2'), ('PUBLIC_RELATIONS_OFFICER', 'Public Relations Officer'), ('PROJECT_MANAGER', 'Project Manager'), ('MEMBERSHIP_DIRECTOR', 'Membership Director'), ('ACADEMIC_DIRECTOR', 'Academic Director'), ('CREATIVE_DIRECTOR', 'Creative Director'), ('MULTIMEDIA_DIRECTOR', 'Multimedia Director'), ('SPORTS_DIRECTOR', 'Sports Director'), ('OUTREACH_DIRECTOR', 'Outreach Director'), ('MANAGEMENT_BUDGET_DIRECTOR', 'Management & Budget Director'), ('COMPLIANCE_DIRECTOR', 'Compliance Director')], default='NONE', max_length=50),
        ),
    ]
