# Generated by Django 4.2.7 on 2026-06-06 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_alter_user_position'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Admin'), ('OFFICER', 'Officer')], default='OFFICER', max_length=10),
        ),
    ]
