# Generated by Django 4.2.7 on 2026-07-02 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_alter_user_position_alter_user_profile_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='officer_id',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
