# Generated by Django 4.2.7 on 2026-07-02 13:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_backfill_officer_ids'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='access_level',
            field=models.CharField(choices=[('FULL_CONTROL', 'Full Control'), ('RESTRICTED', 'Restricted')], default='FULL_CONTROL', max_length=20),
        ),
        migrations.AddField(
            model_name='user',
            name='admin_note',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='user',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_admin_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='user',
            name='registration_status',
            field=models.CharField(choices=[('PENDING', 'Pending Approval'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='APPROVED', max_length=20),
        ),
        migrations.AddField(
            model_name='user',
            name='requested_academic_year',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='user',
            name='requested_department',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='user',
            name='requested_position',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
