# Generated by Django 4.2.7 on 2026-07-02 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_user_access_level_user_admin_note_user_approved_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_delegated',
        ),
        migrations.AlterField(
            model_name='user',
            name='access_level',
            field=models.CharField(choices=[('FULL_CONTROL', 'Full Control'), ('MEMBERSHIP', 'Membership Access'), ('RESTRICTED', 'Restricted')], default='FULL_CONTROL', max_length=20),
        ),
    ]
