# Generated by Django 4.2.7 on 2026-07-24 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_remove_user_is_delegated_alter_user_access_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='display_order',
            field=models.PositiveIntegerField(db_index=True, default=0),
        ),
    ]
